import { StyleSheet } from "react-native";
import { COLORS } from "./colors";

// Refonte maquette Delygest — Page Mes Livraisons & Suivi de Tournée
// Fond #F8F9FC, cartes blanches radius prononcé + ombres légères,
// puces pastel par statut, actions adaptatives au mode d'encaissement.
export const deliveriesStyles = StyleSheet.create({
  // ---------- Header ----------
  header: {
    paddingTop: 48,
    paddingHorizontal: 16,
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  brandName: {
    color: COLORS.white,
    fontSize: 19,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  versionPill: {
    backgroundColor: COLORS.borderVeryLight,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
  },
  versionText: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    flexShrink: 0,
  },
  syncPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: COLORS.successSoft,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
  },
  syncDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.primary,
  },
  syncText: {
    color: COLORS.successText,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  notificationButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  notifBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.danger,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  notifBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 12,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(0,168,89,0.2)",
  },
  avatarText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },

  // ---------- Titre page ----------
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.3,
  },
  pageSubtitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
    marginTop: 3,
  },
  pageSubtitleGain: {
    fontWeight: "800",
    color: COLORS.primary,
  },
  titleActions: {
    flexDirection: "row",
    gap: 8,
    flexShrink: 0,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },

  // ---------- Recherche ----------
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 12,
  },
  searchBox: {
    flex: 1,
    minWidth: 0,
    height: 48,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  searchInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 14,
    color: COLORS.white,
  },
  tuneButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },

  // ---------- Puces période ----------
  periodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 10,
  },
  periodChip: {
    height: 36,
    paddingHorizontal: 15,
    borderRadius: 999,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    justifyContent: "center",
  },
  periodChipActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  periodChipText: {
    fontSize: 13,
    fontWeight: "600",
    color: COLORS.muted,
  },
  periodChipTextActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  calendarButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  calendarButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.successSoft,
  },

  // ---------- Puces statut ----------
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  statusChip: {
    height: 32,
    paddingHorizontal: 13,
    borderRadius: 999,
    backgroundColor: "#E2E7FF",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  statusChipTous: {
    backgroundColor: "#1F2A44",
  },
  statusChipALivrer: {
    backgroundColor: "#FEF3C7",
  },
  statusChipLivree: {
    backgroundColor: "#D1FAE5",
  },
  statusChipAnnulee: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  statusChipActive: {
    borderWidth: 2,
    borderColor: COLORS.primary,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusChipText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.white,
  },
  statusCount: {
    fontSize: 10,
    fontWeight: "800",
    backgroundColor: "rgba(255,255,255,0.75)",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    overflow: "hidden",
    color: COLORS.white,
  },

  // ---------- Liste ----------
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 130,
    gap: 14,
  },
  sectionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    marginTop: 6,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.2,
  },
  sectionBadge: {
    fontSize: 10,
    fontWeight: "800",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: "hidden",
  },

  // ---------- Carte course ----------
  deliveryCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 15,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    gap: 11,
  },
  deliveryCardCancelled: {
    opacity: 0.92,
  },
  cardTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  clientRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  clientName: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.white,
    flexShrink: 1,
  },
  refPill: {
    backgroundColor: COLORS.background,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 7,
    flexShrink: 0,
  },
  refText: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.muted,
  },
  merchantLine: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
    marginTop: 3,
  },
  merchantStrong: {
    fontWeight: "800",
    color: COLORS.white,
  },
  horaireBox: {
    alignItems: "flex-end",
    flexShrink: 0,
  },
  horairePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: "#FEF3C7",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  horaireText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#92400E",
  },
  horaireSub: {
    fontSize: 10,
    color: COLORS.muted,
    marginTop: 3,
  },
  payBadge: {
    fontSize: 10,
    fontWeight: "800",
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    overflow: "hidden",
    flexShrink: 0,
  },
  addressBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 9,
    backgroundColor: COLORS.background,
    borderRadius: 14,
    padding: 11,
  },
  addressMain: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
  },
  addressSub: {
    fontSize: 12,
    color: COLORS.muted,
    marginTop: 2,
  },
  gpsButton: {
    width: 38,
    height: 38,
    borderRadius: 11,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  financeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: 8,
  },
  financeLabel: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: COLORS.muted,
  },
  financeLabelGain: {
    color: COLORS.primary,
  },
  financeAmount: {
    fontSize: 19,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.3,
    marginTop: 2,
  },
  financeAmountGain: {
    fontSize: 16,
    color: COLORS.primary,
  },
  financeAmountMuted: {
    color: COLORS.muted,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 8,
  },
  callButton: {
    width: 50,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#E2E7FF",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mainAction: {
    flex: 1,
    height: 48,
    borderRadius: 14,
    backgroundColor: COLORS.primaryDark,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  mainActionSoft: {
    backgroundColor: "#E2E7FF",
  },
  mainActionText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  mainActionTextDark: {
    color: COLORS.white,
  },

  // ---------- Livrée ----------
  deliveredMeta: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
  },
  deliveredTime: {
    fontWeight: "800",
    color: COLORS.white,
  },
  ecartBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 10,
  },
  ecartLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  ecartAmount: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.white,
  },
  ecartPill: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.danger,
    backgroundColor: COLORS.dangerSoft,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 7,
    overflow: "hidden",
  },
  ecartMotif: {
    fontSize: 10,
    color: COLORS.muted,
    fontStyle: "italic",
  },
  receiptButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 11,
  },
  receiptButtonText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.white,
  },

  // ---------- Incident ----------
  motifBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 10,
  },
  motifText: {
    flex: 1,
    minWidth: 0,
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
  },
  returnLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  returnText: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
    flex: 1,
    minWidth: 0,
  },
  returnAmount: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.muted,
    flexShrink: 0,
  },

  // ---------- Résumé bas de liste ----------
  summaryCard: {
    marginHorizontal: 16,
    backgroundColor: "#E2E7FF",
    borderRadius: 18,
    padding: 16,
    alignItems: "center",
    gap: 4,
  },
  summaryText: {
    fontSize: 12,
    color: COLORS.muted,
    textAlign: "center",
  },
  summaryAmount: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.white,
    textAlign: "center",
  },
  summarySub: {
    fontSize: 11,
    fontWeight: "400",
    color: COLORS.muted,
  },

  // ---------- Feuille période (jour / mois) ----------
  sheetOverlay: {
    flex: 1,
    backgroundColor: "rgba(19,27,46,0.5)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 34,
    gap: 14,
    maxHeight: "80%",
  },
  dragHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D8DEE9",
    alignSelf: "center",
  },
  sheetToggle: {
    flexDirection: "row",
    backgroundColor: "#EEF1F6",
    borderRadius: 14,
    padding: 4,
    gap: 4,
  },
  sheetToggleBtn: {
    flex: 1,
    minHeight: 44,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetToggleBtnActive: {
    backgroundColor: COLORS.primaryDark,
  },
  sheetToggleText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.muted,
  },
  sheetToggleTextActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  yearRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  yearNav: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
  },
  yearText: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.white,
  },
  monthGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  monthCell: {
    width: "31%",
    flexGrow: 1,
    height: 46,
    borderRadius: 13,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
  },
  monthCellActive: {
    backgroundColor: COLORS.primaryDark,
  },
  monthCellCurrent: {
    borderWidth: 1.5,
    borderColor: COLORS.primary,
  },
  monthCellText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.muted,
  },
  monthCellTextActive: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  sheetClear: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  sheetClearText: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.muted,
  },

  // ---------- Tri inline (sans Modal natif) ----------
  sortOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 60,
    elevation: 60,
    backgroundColor: "rgba(19,27,46,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  sortBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  sortOption: {
    height: 48,
    borderRadius: 14,
    backgroundColor: COLORS.primaryDark,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  sortOptionInactive: {
    backgroundColor: "#E2E7FF",
  },

  // ---------- États vides / modales ----------
  emptyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 26,
    marginHorizontal: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  emptyText: {
    color: COLORS.muted,
    textAlign: "center",
    fontSize: 13,
    marginTop: 10,
    lineHeight: 18,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(19,27,46,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    width: "100%",
    maxWidth: 360,
    gap: 12,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: COLORS.white,
    textAlign: "center",
  },
  modalMessage: {
    fontSize: 13,
    color: COLORS.muted,
    textAlign: "center",
    lineHeight: 18,
  },
  modalSummary: {
    backgroundColor: COLORS.background,
    borderRadius: 14,
    padding: 12,
    gap: 7,
  },
  modalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  modalLabel: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
  },
  modalValue: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
  },
  modalInput: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    paddingHorizontal: 13,
    paddingVertical: 12,
    fontSize: 13,
    color: COLORS.white,
    minHeight: 48,
    textAlignVertical: "top",
  },
  modalButtons: {
    flexDirection: "row",
    gap: 10,
  },
  modalButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  modalButtonCancel: {
    backgroundColor: COLORS.borderVeryLight,
  },
  modalButtonPrimary: {
    backgroundColor: COLORS.primaryDark,
  },
  modalButtonDanger: {
    backgroundColor: COLORS.danger,
  },
  modalButtonTextCancel: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.white,
  },
  modalButtonTextPrimary: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },

  // ---------- Legacy (DeliveryCard orphelin — conservé) ----------
  deliveryContent: { flex: 1 },
  deliveryHeader: { flexDirection: "row", justifyContent: "space-between" },
  statusTimeContainer: { flexDirection: "row", alignItems: "center", gap: 8 },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  statusText: { fontSize: 10, fontWeight: "500" },
  timeText: { color: COLORS.muted, fontSize: 12, fontWeight: "bold" },
  feeText: { color: COLORS.primary, fontSize: 14, fontWeight: "bold" },
  addressContainer: { gap: 4, marginTop: 8 },
  addressLine: { flexDirection: "row", alignItems: "center", gap: 6 },
  addressDot: { width: 8, height: 8, borderRadius: 4 },
  addressText: { color: COLORS.white, fontSize: 13, flex: 1 },
  deliveryDetails: { marginTop: 8, gap: 2 },
  paymentTypeText: { fontSize: 12, color: COLORS.muted },
  encaisseText: { fontSize: 13, fontWeight: "700", color: COLORS.white },
  reverserText: { fontSize: 12, color: COLORS.warning },
  actionsContainer: { flexDirection: "row", gap: 8, marginTop: 10 },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  actionButtonDanger: { backgroundColor: COLORS.dangerSoft },
  actionButtonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 13 },
  checkboxContainer: { padding: 4 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  checkboxDisabled: { opacity: 0.6 },
});
