import { StyleSheet } from "react-native";
import { COLORS } from "./colors";

// Refonte maquette Delygest — Page Détail d'une Livraison
// Fond #F8F9FC, cartes blanches radius prononcé + ombres légères,
// badges pastel, gros boutons tactiles (≥48px).
export const deliveryDetailStyles = StyleSheet.create({
  // ---------- Loading / erreur ----------
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
  },
  loadingText: {
    marginTop: 16,
    color: COLORS.muted,
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
    padding: 20,
  },
  errorText: {
    marginTop: 16,
    color: COLORS.danger,
    fontSize: 18,
    fontWeight: "600",
  },
  backButton: {
    marginTop: 24,
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: COLORS.card,
    borderRadius: 8,
  },
  backButtonText: {
    color: COLORS.primary,
    fontSize: 16,
    fontWeight: "500",
  },

  // ---------- Header ----------
  header: {
    paddingTop: 48,
    paddingHorizontal: 16,
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  backButtonHeader: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.white,
    flex: 1,
    minWidth: 0,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
  },
  syncPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: COLORS.successSoft,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
  },
  syncDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.primary,
  },
  syncText: {
    color: COLORS.successText,
    fontSize: 11,
    fontWeight: "800",
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(0,168,89,0.2)",
  },
  avatarText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },

  // ---------- Scroll / cartes ----------
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 170,
    gap: 12,
    paddingTop: 14,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 15,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    gap: 10,
  },
  sectionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.2,
  },

  // ---------- Hero destinataire ----------
  refRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  refLabel: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
    color: COLORS.muted,
  },
  refPill: {
    backgroundColor: "rgba(0,168,89,0.12)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 7,
  },
  refText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.primary,
  },
  clientName: {
    fontSize: 23,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.4,
  },
  statusPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 6,
    borderRadius: 999,
    flexShrink: 0,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
  },
  statusText: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  scheduleBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  scheduleText: {
    fontSize: 13,
    color: COLORS.muted,
    fontWeight: "500",
  },
  scheduleStrong: {
    fontWeight: "800",
    color: COLORS.white,
  },
  heroTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },

  // ---------- Boutons urgence ----------
  urgentRow: {
    flexDirection: "row",
    gap: 10,
    paddingHorizontal: 16,
  },
  urgentButton: {
    flex: 1,
    minHeight: 56,
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    paddingHorizontal: 12,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 4,
  },
  urgentButtonCall: {
    backgroundColor: COLORS.primary,
  },
  urgentButtonGps: {
    backgroundColor: "#006398",
  },
  urgentIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.22)",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  urgentLabel: {
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.88)",
  },
  urgentValue: {
    fontSize: 13,
    fontWeight: "800",
    color: "#FFFFFF",
  },

  // ---------- Mini-carte ----------
  communePill: {
    backgroundColor: COLORS.background,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 8,
    flexShrink: 0,
  },
  communeText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.muted,
  },
  mapPreview: {
    height: 128,
    borderRadius: 14,
    backgroundColor: "#E4EAF2",
    overflow: "hidden",
    position: "relative",
    justifyContent: "flex-end",
  },
  mapGrid: {
    ...StyleSheet.absoluteFillObject,
  },
  mapGridLineH: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  mapGridLineV: {
    position: "absolute",
    top: 0,
    bottom: 0,
    width: 1,
    backgroundColor: "rgba(255,255,255,0.7)",
  },
  mapRoad: {
    position: "absolute",
    backgroundColor: "#FFFFFF",
    borderRadius: 3,
    shadowColor: "#94A3B8",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.4,
    shadowRadius: 2,
    elevation: 1,
  },
  mapPin: {
    position: "absolute",
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: "#FFFFFF",
    shadowColor: "#0F6841",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 5,
    elevation: 5,
  },
  mapFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(19,27,46,0.72)",
    margin: 9,
    borderRadius: 11,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  mapFooterLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
  },
  mapFooterText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#FFFFFF",
    flexShrink: 1,
  },
  mapFooterPill: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    flexShrink: 0,
  },
  mapFooterPillText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  landmarkBox: {
    flexDirection: "row",
    gap: 9,
    backgroundColor: COLORS.background,
    borderRadius: 13,
    padding: 11,
  },
  landmarkMain: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
  },
  landmarkSub: {
    fontSize: 12,
    color: COLORS.muted,
    marginTop: 2,
  },
  addressActions: {
    flexDirection: "row",
    gap: 8,
  },
  addressAction: {
    flex: 1,
    minHeight: 44,
    borderRadius: 12,
    backgroundColor: COLORS.background,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  addressActionText: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.muted,
  },

  // ---------- Trésorerie ----------
  cashBanner: {
    borderRadius: 15,
    backgroundColor: COLORS.primary,
    padding: 14,
    gap: 4,
    overflow: "hidden",
  },
  cashLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: "#9FF5C1",
  },
  cashRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  cashAmount: {
    fontSize: 26,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: -0.6,
  },
  cashUnit: {
    fontSize: 13,
    fontWeight: "600",
  },
  cashTag: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: "#FFFFFF",
    backgroundColor: "rgba(255,255,255,0.22)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 7,
    overflow: "hidden",
    flexShrink: 0,
  },
  moneyLines: {
    backgroundColor: COLORS.background,
    borderRadius: 13,
    padding: 12,
    gap: 9,
  },
  moneyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  moneyLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
    flex: 1,
    minWidth: 0,
  },
  moneyValue: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
    flexShrink: 0,
  },
  moneyDivider: {
    height: 1,
    backgroundColor: "#D8DEE9",
  },
  gainBox: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(0,168,89,0.12)",
    borderRadius: 12,
    padding: 10,
  },
  gainLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.successText,
    flex: 1,
    minWidth: 0,
  },
  gainValue: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.primary,
    flexShrink: 0,
  },

  // ---------- Note terrain ----------
  noteBox: {
    flexDirection: "row",
    gap: 9,
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "#FDE68A",
    borderRadius: 13,
    padding: 12,
  },
  noteText: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    lineHeight: 19,
    color: "#92400E",
    fontWeight: "500",
  },

  // ---------- Boutique ----------
  merchantRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 14,
    padding: 11,
  },
  merchantLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  merchantAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#006398",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  merchantAvatarText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  merchantName: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.white,
  },
  merchantSub: {
    fontSize: 11,
    color: COLORS.muted,
    marginTop: 2,
  },
  merchantCall: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  verifiedPill: {
    fontSize: 10,
    fontWeight: "800",
    color: "#006398",
    backgroundColor: "#DBEAFE",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    overflow: "hidden",
    flexShrink: 0,
  },
  geranteLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 2,
  },
  geranteLabel: {
    fontSize: 12,
    color: COLORS.muted,
  },
  geranteValue: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.white,
    flexShrink: 0,
  },

  // ---------- Timeline ----------
  timelineRow: {
    flexDirection: "row",
    gap: 12,
  },
  timelineRail: {
    alignItems: "center",
    width: 24,
  },
  timelineDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  timelineLine: {
    width: 2,
    flex: 1,
    backgroundColor: COLORS.borderLight,
    marginVertical: 3,
    minHeight: 14,
  },
  timelineBody: {
    flex: 1,
    minWidth: 0,
    paddingBottom: 14,
  },
  timelineHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  timelineTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
    flexShrink: 1,
  },
  timelineTitleActive: {
    color: "#B45309",
  },
  timelineTime: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.muted,
    flexShrink: 0,
  },
  timelineTimeActive: {
    color: "#B45309",
  },
  timelineSub: {
    fontSize: 12,
    color: COLORS.muted,
    marginTop: 2,
  },

  // ---------- Barre d'action fixe ----------
  actionBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 26,
    backgroundColor: "rgba(255,255,255,0.96)",
    borderTopWidth: 1,
    borderTopColor: COLORS.borderLight,
    gap: 8,
  },
  primaryButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: COLORS.primaryDark,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    shadowColor: "#0F6841",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  primaryButtonLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  primaryButtonText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  primaryButtonAmount: {
    backgroundColor: "rgba(255,255,255,0.18)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  primaryButtonAmountText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  secondaryButton: {
    height: 46,
    borderRadius: 14,
    backgroundColor: COLORS.background,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  secondaryButtonText: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.danger,
  },
  manageRow: {
    flexDirection: "row",
    gap: 8,
  },
  manageButton: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  manageButtonText: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.muted,
  },
  manageButtonDangerText: {
    color: COLORS.danger,
  },
  readOnlyBox: {
    alignItems: "center",
    gap: 4,
    paddingVertical: 4,
  },
  readOnlyText: {
    fontSize: 13,
    color: COLORS.muted,
    fontStyle: "italic",
    textAlign: "center",
  },

  // ---------- Bottom sheets / modales ----------
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(19,27,46,0.55)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    paddingBottom: 34,
    gap: 13,
    maxHeight: "85%",
  },
  dragHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#D8DEE9",
    alignSelf: "center",
  },
  sheetHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  sheetTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: COLORS.white,
    flexShrink: 1,
  },
  sheetClose: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sheetText: {
    fontSize: 13,
    color: COLORS.muted,
    lineHeight: 19,
  },
  sheetSummary: {
    backgroundColor: COLORS.background,
    borderRadius: 14,
    padding: 14,
    gap: 9,
  },
  sheetRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  sheetLabel: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
  },
  sheetValue: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
  },
  sheetValueGreen: {
    color: COLORS.primary,
  },
  gpsOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 14,
    padding: 14,
  },
  gpsOptionLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
  },
  gpsOptionName: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.white,
  },
  issueOption: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 14,
    padding: 14,
    minHeight: 52,
  },
  issueOptionText: {
    fontSize: 14,
    fontWeight: "700",
    color: COLORS.white,
    flex: 1,
    minWidth: 0,
  },
  modalInput: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    paddingHorizontal: 13,
    paddingVertical: 11,
    fontSize: 13,
    color: COLORS.white,
    minHeight: 48,
    textAlignVertical: "top",
  },
  sheetButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  sheetButtonText: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
  },
});
