import { StyleSheet } from "react-native";
import { COLORS } from "./colors";

// Refonte maquette Delygest — Page Reversements Commerçants
// Fond #F8F9FC, cartes blanches radius prononcé + ombres légères,
// hero sombre bleu nuit, canaux colorés, jauge vert/rouge.
export const merchantAccountingStyles = StyleSheet.create({
  // ---------- Header ----------
  header: {
    paddingTop: 48,
    paddingHorizontal: 16,
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  brandName: {
    color: COLORS.white,
    fontSize: 19,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  versionPill: {
    backgroundColor: COLORS.borderVeryLight,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
  },
  versionText: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    flexShrink: 0,
  },
  syncPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: COLORS.successSoft,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
  },
  syncDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.primary,
  },
  syncText: {
    color: COLORS.successText,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  notificationButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  notifBadge: {
    position: "absolute",
    top: 6,
    right: 6,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.danger,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  notifBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
    lineHeight: 12,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(0,168,89,0.2)",
  },
  avatarText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },

  // ---------- Scroll ----------
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 130,
    gap: 14,
  },

  // ---------- Titre section ----------
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  pageTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.2,
  },
  pageSubtitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
    marginTop: 3,
  },
  securePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#E2E7FF",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    flexShrink: 0,
  },
  secureText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.infoText,
  },

  // ---------- Hero sombre ----------
  heroCard: {
    borderRadius: 20,
    padding: 18,
    marginHorizontal: 16,
    backgroundColor: "#1F2A44",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 5,
    gap: 10,
    overflow: "hidden",
  },
  heroTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  heroLabel: {
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
    color: "#9FF5C1",
    flex: 1,
    minWidth: 0,
  },
  heroCountPill: {
    backgroundColor: "rgba(159,245,193,0.18)",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    flexShrink: 0,
  },
  heroCountText: {
    fontSize: 10,
    fontWeight: "800",
    color: "#9FF5C1",
  },
  heroAmountRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
  },
  heroAmount: {
    fontSize: 33,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: -0.8,
  },
  heroCurrency: {
    fontSize: 16,
    fontWeight: "700",
    color: "#9FF5C1",
  },
  heroInner: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 14,
    padding: 12,
  },
  heroInnerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  heroInnerLabel: {
    fontSize: 12,
    color: "#D8DEE9",
    fontWeight: "500",
    flexShrink: 1,
  },
  heroInnerValue: {
    fontSize: 15,
    fontWeight: "800",
    color: "#FFFFFF",
    flexShrink: 0,
  },

  // ---------- Tabs ----------
  tabsRow: {
    flexDirection: "row",
    backgroundColor: "#EEF1F6",
    borderRadius: 14,
    padding: 4,
    gap: 4,
    marginHorizontal: 16,
  },
  tab: {
    flex: 1,
    minHeight: 44,
    borderRadius: 11,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
  },
  tabActive: {
    backgroundColor: "#FFFFFF",
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  tabText: {
    fontSize: 12.5,
    fontWeight: "700",
    color: COLORS.muted,
  },
  tabTextActive: {
    color: COLORS.white,
    fontWeight: "800",
  },
  tabCount: {
    fontSize: 10,
    fontWeight: "800",
    backgroundColor: COLORS.successSoft,
    color: COLORS.successText,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    overflow: "hidden",
  },

  // ---------- Carte blanche ----------
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    gap: 12,
  },

  // ---------- Focus marchand ----------
  merchantHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
  },
  merchantLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    flex: 1,
    minWidth: 0,
  },
  merchantAvatar: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: "#FFDDB8",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  merchantNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  merchantName: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.white,
    flexShrink: 1,
  },
  merchantSub: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
    marginTop: 3,
  },
  merchantDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: COLORS.primary,
  },
  collectedBox: {
    alignItems: "flex-end",
    flexShrink: 0,
  },
  collectedLabel: {
    fontSize: 9,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    color: COLORS.muted,
  },
  collectedValue: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.primary,
    marginTop: 2,
  },
  dueLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#FFFBEB",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "#FDE68A",
  },
  dueLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#92400E",
  },
  dueValue: {
    fontSize: 16,
    fontWeight: "800",
    color: "#92400E",
  },

  // ---------- Bloc versement ----------
  payBox: {
    backgroundColor: "#F6F8FB",
    borderRadius: 16,
    padding: 14,
    gap: 12,
  },
  payHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  payTitle: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.white,
  },
  partialPill: {
    backgroundColor: "#E2E7FF",
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 999,
    flexShrink: 0,
  },
  partialText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.infoText,
  },
  fieldLabel: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
  },
  amountBox: {
    height: 50,
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingHorizontal: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  amountBoxError: {
    borderColor: COLORS.danger,
    backgroundColor: COLORS.dangerSoft,
  },
  amountInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 17,
    fontWeight: "800",
    color: COLORS.white,
  },
  amountSuffix: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.muted,
    flexShrink: 0,
  },
  gaugeBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  gaugeRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  gaugeText: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
  },
  gaugeStrongGreen: {
    fontWeight: "800",
    color: COLORS.primary,
  },
  gaugeStrongRed: {
    fontWeight: "800",
    color: COLORS.danger,
  },
  gaugeTrack: {
    height: 10,
    borderRadius: 999,
    backgroundColor: "#FBD5D5",
    overflow: "hidden",
    flexDirection: "row",
  },
  gaugeFill: {
    height: "100%",
    backgroundColor: COLORS.primaryDark,
    borderTopLeftRadius: 999,
    borderBottomLeftRadius: 999,
  },
  gaugeScale: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  gaugeScaleText: {
    fontSize: 10,
    color: COLORS.muted,
    fontWeight: "500",
  },
  channelGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  channelButton: {
    flex: 1,
    minWidth: "46%",
    minHeight: 50,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1.5,
    borderColor: COLORS.borderLight,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    gap: 6,
  },
  channelButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: "#EAF6EF",
  },
  channelLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  channelDot: {
    width: 11,
    height: 11,
    borderRadius: 5.5,
    flexShrink: 0,
  },
  channelLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.white,
    flexShrink: 1,
  },
  refBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 4,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    minHeight: 48,
  },
  refInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    color: COLORS.white,
    paddingVertical: 10,
  },
  confirmButton: {
    height: 52,
    borderRadius: 14,
    backgroundColor: COLORS.primaryDark,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    shadowColor: "#0F6841",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  confirmButtonDisabled: {
    opacity: 0.55,
  },
  confirmText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  settleAllButton: {
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  settleAllText: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.primary,
  },
  errorText: {
    fontSize: 12,
    color: COLORS.danger,
    fontStyle: "italic",
  },

  // ---------- Autres commerçants ----------
  sectionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.white,
  },
  sectionCount: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.muted,
  },
  otherCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 14,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  otherLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    flex: 1,
    minWidth: 0,
  },
  otherAvatar: {
    width: 44,
    height: 44,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  otherRight: {
    alignItems: "flex-end",
    gap: 6,
    flexShrink: 0,
  },
  otherAmount: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.white,
  },
  reverseButton: {
    height: 34,
    paddingHorizontal: 13,
    borderRadius: 10,
    backgroundColor: "#E2E7FF",
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  reverseButtonText: {
    fontSize: 12,
    fontWeight: "800",
    color: COLORS.primary,
  },
  reverseButtonActive: {
    backgroundColor: COLORS.primaryDark,
  },
  reverseButtonTextActive: {
    color: "#FFFFFF",
  },

  // ---------- Partager ----------
  shareButton: {
    height: 50,
    marginHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: COLORS.borderLight,
    backgroundColor: "#FFFFFF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  shareButtonText: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
  },

  // ---------- Historique ----------
  historyRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F6F8FB",
    borderRadius: 14,
    padding: 12,
  },
  historyChannel: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },

  // ---------- Cartes dépliables ----------
  expandChevron: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  expandedBox: {
    backgroundColor: "#F6F8FB",
    borderRadius: 14,
    padding: 10,
    gap: 8,
  },
  expandedTitle: {
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: COLORS.muted,
  },
  miniDeliveryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  miniDeliveryName: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
  },
  miniDeliverySub: {
    fontSize: 11,
    color: COLORS.muted,
    fontWeight: "500",
    marginTop: 2,
  },
  miniDeliveryAmount: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.primaryDark,
    flexShrink: 0,
  },
  financeLine: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  financeLabel: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
  },
  financeValue: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
  },

  // ---------- État vide ----------
  emptyCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 26,
    marginHorizontal: 16,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
  },
  emptyText: {
    color: COLORS.muted,
    textAlign: "center",
    fontSize: 13,
    marginTop: 10,
    lineHeight: 18,
  },

  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
});
