import { StyleSheet } from "react-native";
import { COLORS } from "./colors";

export const settingsStyles = StyleSheet.create({
  header: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 60,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderVeryLight,
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.white,
  },
  saveButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.primary,
  },
  content: {
    flex: 1,
    marginTop: 124,
  },
  scrollContent: {
    paddingBottom: 100,
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  profileImageContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  profileImage: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: '#1a331a',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 4,
    borderColor: '#1a331a',
    overflow: 'hidden',
  },
  onlineIndicator: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  onlineDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: COLORS.primary,
  },
  profileName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.white,
    marginBottom: 4,
  },
  profileSubtitle: {
    fontSize: 14,
    color: COLORS.muted,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: COLORS.muted,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 8,
    marginLeft: 8,
  },
  cardItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderVeryLight,
  },
  cardItemNoBorder: {
    borderBottomWidth: 0,
  },
  cardItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  cardItemLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.white,
  },
  cardItemLabelDanger: {
    fontSize: 16,
    fontWeight: '500',
    color: COLORS.danger,
  },
  cardItemInput: {
    flex: 1,
    textAlign: 'right',
    fontSize: 16,
    color: COLORS.muted,
    padding: 0,
  },
  cardItemRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardItemValue: {
    fontSize: 16,
    color: COLORS.muted,
  },
  goalInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  goalInput: {
    fontSize: 16,
    fontWeight: '600',
    color: COLORS.muted,
    textAlign: 'right',
    minWidth: 60,
    padding: 0,
  },
  currency: {
    fontSize: 16,
    color: COLORS.muted,
    marginLeft: 4,
  },
  notificationContent: {
    flexDirection: 'column',
    gap: 2,
  },
  notificationSubtitle: {
    fontSize: 12,
    color: COLORS.muted,
  },
  cardItemDanger: {
    backgroundColor: COLORS.dangerSoft,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: COLORS.card,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 28,
    paddingVertical: 16,
    marginHorizontal: 20,
    marginTop: 16,
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.danger,
  },
  versionText: {
    textAlign: 'center',
    fontSize: 12,
    color: COLORS.muted,
    marginTop: 24,
  },


  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: COLORS.muted,
  },
  authErrorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  authErrorText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.danger,
    marginTop: 16,
  },
  authErrorButton: {
    marginTop: 24,
    backgroundColor: COLORS.primary,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 12,
  },
  authErrorButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.white,
  },
   userIdText: {
    fontSize: 12,
    color: COLORS.muted,
    marginTop: 4,
    opacity: 0.7,
  },
});