import { StyleSheet } from "react-native";
import { COLORS } from "./colors";

// Refonte maquette Delygest — Profil & Paramètres Livreur
// Fond #F8F9FC, cartes blanches radius prononcé + ombres légères,
// badges pastel, switches verts, SOS rouge.
export const settingsStyles = StyleSheet.create({
  // ---------- Loading / erreur ----------
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
    gap: 10,
  },
  loadingText: {
    color: COLORS.muted,
    fontSize: 15,
  },
  authErrorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: COLORS.background,
    padding: 24,
    gap: 12,
  },
  authErrorText: {
    color: COLORS.danger,
    fontSize: 17,
    fontWeight: "700",
  },
  authErrorButton: {
    backgroundColor: COLORS.primaryDark,
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 12,
  },
  authErrorButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
  },

  // ---------- Header ----------
  header: {
    paddingTop: 48,
    paddingHorizontal: 16,
    paddingBottom: 10,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderLight,
  },
  headerContent: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
    minWidth: 0,
  },
  brandName: {
    color: COLORS.white,
    fontSize: 19,
    fontWeight: "800",
    letterSpacing: -0.3,
  },
  versionPill: {
    backgroundColor: COLORS.borderVeryLight,
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
  },
  versionText: {
    color: COLORS.muted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.4,
  },
  headerActions: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    flexShrink: 0,
  },
  onlinePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: COLORS.successSoft,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 999,
  },
  onlineDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: COLORS.primary,
  },
  onlineText: {
    color: COLORS.successText,
    fontSize: 11,
    fontWeight: "800",
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "rgba(0,168,89,0.25)",
  },
  avatarText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },

  // ---------- Scroll / cartes ----------
  scrollView: { flex: 1 },
  scrollContent: {
    paddingBottom: 130,
    gap: 14,
    paddingTop: 14,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    padding: 15,
    marginHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    gap: 11,
  },
  cardHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  cardHeadLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    flex: 1,
    minWidth: 0,
  },
  cardHeadIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: COLORS.background,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.2,
  },
  cardSubtitle: {
    fontSize: 11,
    color: COLORS.muted,
    marginTop: 1,
  },

  // ---------- Profil ----------
  profileTop: {
    flexDirection: "row",
    gap: 13,
    alignItems: "flex-start",
  },
  avatarWrap: {
    position: "relative",
    flexShrink: 0,
  },
  bigAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#0F6841",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 4,
  },
  bigAvatarText: {
    fontSize: 28,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  presenceDot: {
    position: "absolute",
    bottom: 2,
    right: 2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  presenceInner: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: COLORS.primary,
  },
  profileNameRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.3,
    flexShrink: 1,
  },
  editButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: COLORS.background,
    paddingHorizontal: 11,
    paddingVertical: 7,
    borderRadius: 999,
    flexShrink: 0,
  },
  editButtonText: {
    fontSize: 11,
    fontWeight: "800",
    color: COLORS.muted,
  },
  matriculeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 5,
  },
  matricule: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.primary,
    backgroundColor: "rgba(0,168,89,0.12)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 7,
    overflow: "hidden",
  },
  vehicleTag: {
    fontSize: 11,
    color: COLORS.muted,
    fontWeight: "600",
  },
  repBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#FFFBEB",
    borderWidth: 1,
    borderColor: "#FDE68A",
    alignSelf: "flex-start",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    marginTop: 9,
  },
  repText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#92400E",
  },
  repSub: {
    fontSize: 10,
    fontWeight: "500",
    color: "#B45309",
  },
  zoneBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 10,
  },
  zoneText: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
    flex: 1,
    minWidth: 0,
  },
  zoneStrong: {
    fontWeight: "800",
    color: COLORS.white,
  },

  // ---------- Bento stats ----------
  sectionHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginHorizontal: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.2,
  },
  tierPill: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.7,
    textTransform: "uppercase",
    color: COLORS.primary,
  },
  bentoGrid: {
    gap: 10,
    paddingHorizontal: 16,
  },
  bentoRow: {
    flexDirection: "row",
    gap: 10,
  },
  bentoCell: {
    flex: 1,
    minWidth: 0,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 13,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    shadowColor: "#0F172A",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    gap: 2,
  },
  bentoHead: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bentoLabel: {
    fontSize: 12,
    color: COLORS.muted,
    fontWeight: "500",
  },
  bentoValue: {
    fontSize: 21,
    fontWeight: "800",
    color: COLORS.white,
    letterSpacing: -0.4,
    marginTop: 3,
  },
  bentoValueGreen: {
    color: COLORS.primary,
  },
  bentoSub: {
    fontSize: 10,
    color: COLORS.muted,
  },

  // ---------- Lignes génériques ----------
  infoRow: {
    flexDirection: "row",
    gap: 11,
    backgroundColor: COLORS.background,
    borderRadius: 13,
    padding: 11,
    alignItems: "flex-start",
  },
  infoBody: {
    flex: 1,
    minWidth: 0,
  },
  infoTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  infoTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
    flexShrink: 1,
  },
  infoSub: {
    fontSize: 11,
    color: COLORS.muted,
    marginTop: 2,
  },
  miniPill: {
    fontSize: 9,
    fontWeight: "800",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 7,
    overflow: "hidden",
    flexShrink: 0,
  },
  okPill: {
    color: COLORS.successText,
    backgroundColor: COLORS.successSoft,
  },
  neutralPill: {
    color: COLORS.muted,
    backgroundColor: "#E2E7FF",
  },
  goldPill: {
    color: "#92400E",
    backgroundColor: "#FDE68A",
  },

  // ---------- Mobile Money ----------
  mmRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 14,
    padding: 11,
  },
  mmLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    flex: 1,
    minWidth: 0,
  },
  mmIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  mmName: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.white,
  },
  mmNumber: {
    fontSize: 12,
    fontWeight: "700",
    color: COLORS.muted,
    marginTop: 2,
  },
  mmTag: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
  },
  mmTagText: {
    fontSize: 10,
    fontWeight: "800",
  },
  switchRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  switchBody: {
    flexDirection: "row",
    gap: 9,
    flex: 1,
    minWidth: 0,
    alignItems: "flex-start",
  },

  // ---------- GPS chips ----------
  gpsGrid: {
    flexDirection: "row",
    gap: 8,
  },
  gpsChip: {
    flex: 1,
    minWidth: 0,
    borderRadius: 13,
    backgroundColor: COLORS.background,
    paddingVertical: 11,
    alignItems: "center",
    gap: 5,
  },
  gpsChipActive: {
    backgroundColor: "rgba(0,168,89,0.12)",
    borderWidth: 1.5,
    borderColor: COLORS.primary,
  },
  gpsChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: COLORS.muted,
  },
  gpsChipTextActive: {
    color: COLORS.primaryDark,
    fontWeight: "800",
  },
  gpsDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "transparent",
  },
  gpsDotActive: {
    backgroundColor: COLORS.primary,
  },

  // ---------- Assistance / footer ----------
  waCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(37,211,102,0.12)",
    borderWidth: 1,
    borderColor: "rgba(37,211,102,0.35)",
    borderRadius: 15,
    padding: 13,
    marginHorizontal: 16,
  },
  waLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 11,
    flex: 1,
    minWidth: 0,
  },
  waIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "#25D366",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sosButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: COLORS.dangerSoft,
    borderWidth: 1,
    borderColor: COLORS.danger,
    borderRadius: 15,
    padding: 14,
    marginHorizontal: 16,
  },
  sosText: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.danger,
  },
  versionPillCenter: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  versionPillDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: COLORS.primary,
  },
  versionPillText: {
    fontSize: 10,
    fontWeight: "800",
    color: COLORS.muted,
  },
  logoutButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    backgroundColor: "#EDE9FE",
    borderRadius: 14,
    padding: 14,
    marginHorizontal: 16,
  },
  logoutText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#5B5BD6",
  },
  deviceText: {
    fontSize: 10,
    color: COLORS.muted,
    textAlign: "center",
    paddingHorizontal: 24,
  },

  // ---------- Champs / objectifs / compte ----------
  fieldRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 13,
    padding: 11,
  },
  fieldLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    fontSize: 13,
    fontWeight: "700",
    color: COLORS.white,
    flex: 1,
    minWidth: 0,
  },
  goalBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 10,
    paddingHorizontal: 9,
    paddingVertical: 7,
    flexShrink: 0,
  },
  goalInput: {
    fontSize: 14,
    fontWeight: "800",
    color: COLORS.white,
    minWidth: 64,
    textAlign: "right",
    padding: 0,
  },
  goalUnit: {
    fontSize: 10,
    fontWeight: "700",
    color: COLORS.muted,
  },
  linkRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: COLORS.background,
    borderRadius: 13,
    padding: 13,
  },
  dangerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    backgroundColor: COLORS.background,
    borderRadius: 13,
    padding: 13,
  },
  dangerText: {
    fontSize: 13,
    fontWeight: "800",
    color: COLORS.danger,
  },
  passwordBox: {
    gap: 9,
    backgroundColor: COLORS.background,
    borderRadius: 13,
    padding: 12,
  },
  passwordInput: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    borderRadius: 11,
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 13,
    color: COLORS.white,
  },
  passwordInputError: {
    borderColor: COLORS.danger,
  },
  passwordError: {
    fontSize: 11,
    color: COLORS.danger,
    fontStyle: "italic",
  },
  passwordHint: {
    fontSize: 11,
    color: COLORS.muted,
  },
  passwordButton: {
    backgroundColor: COLORS.primaryDark,
    borderRadius: 12,
    padding: 13,
    alignItems: "center",
  },
  passwordButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 14,
  },

  // ---------- Toast ----------
  toast: {
    position: "absolute",
    top: 104,
    left: 16,
    right: 16,
    zIndex: 80,
    elevation: 80,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#131B2E",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
  },
  toastLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
    flex: 1,
    minWidth: 0,
  },
  toastText: {
    fontSize: 12,
    fontWeight: "700",
    color: "#FFFFFF",
    flexShrink: 1,
  },
  toastSync: {
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.6,
    color: "#9FF5C1",
    flexShrink: 0,
  },

  // ---------- Modales ----------
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(19,27,46,0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    width: "100%",
    maxWidth: 360,
    gap: 12,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: COLORS.white,
    textAlign: "center",
  },
  modalMessage: {
    fontSize: 13,
    color: COLORS.muted,
    textAlign: "center",
    lineHeight: 18,
  },
  modalInput: {
    backgroundColor: COLORS.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.borderLight,
    paddingHorizontal: 13,
    paddingVertical: 12,
    fontSize: 14,
    color: COLORS.white,
  },
  modalButtons: {
    flexDirection: "row",
    gap: 10,
  },
  modalButton: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  modalButtonCancel: {
    backgroundColor: COLORS.borderVeryLight,
  },
  modalButtonDanger: {
    backgroundColor: COLORS.danger,
  },
  modalButtonPrimary: {
    backgroundColor: COLORS.primaryDark,
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: "800",
  },
  modalButtonTextCancel: {
    color: COLORS.white,
  },
  modalButtonTextDanger: {
    color: "#FFFFFF",
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.3)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  loadingContent: {
    backgroundColor: "#FFFFFF",
    padding: 24,
    borderRadius: 16,
    alignItems: "center",
    gap: 12,
  },
});
